### ISSUE TITLE
UserCode will run twice when save in protocol

### ISSUE THREAD

**Issue by sppmg** [JaneliaSciComp/Wavesurfer#240]
Hi
I know what problem in #239 . I set class name and  save the protocol, so when I open protocol, It run twice. And I open a figure in my code, so DAQ association still in memory.

I wrote a MWE for you (send to your mail). Here post effective code.

Oh, I use version 0.97 with matlab 2018a. And use 2 daq.

```matlab
classdef
    methods
        function self = wsuc()
            self.usrDaq = setEncoder(self.usrDaq) ; % association will block.
            self.usrDaq = setDio(self.usrDaq) ; % no effect 
            figure('UserData', self.usrDaq) ; % keep association 
            
            fprintf('Hi, I was born for trainer. I am ready !!\n');
        end
    end
end  % classdef



function usrDaq = setEncoder(usrDaq)
    isIntClock = true;
    devName = 'Dev4' ;

    if isempty(usrDaq)
        usrDaq.daq = daq.createSession('ni');
    end
    addCounterInputChannel(usrDaq.daq, devName, 'ctr0', 'Position');
    
    if isIntClock
        addAnalogInputChannel(usrDaq.daq, devName, 'ai0', 'Voltage'); % for clock
    else
        addClockConnection(usrDaq.daq, 'External', [devName,'/PFI5'], 'ScanClock') ;
    end
end

function usrDaq = setDio(usrDaq)
    devName = 'Dev4' ;

    if isempty(usrDaq)
        usrDaq.daq = daq.createSession('ni');
    end
    addDigitalChannel(usrDaq.daq, devName, 'Port0/Line0', 'OutputOnly');
end
```
![default](https://user-images.githubusercontent.com/6098465/43513477-6a2406ae-95b0-11e8-87f5-781e642e3a03.png)

If you comment `figure()` line, the error will not happen.

**Comment by adamltaylor** [comment]
The issue here is that you need to move the initialization code to the wake() method of the user class.  Also, the creation of resources like figures and daq sessions should only be done if the parent of the user object is of type ws.WavesurferModel and .IsITheOneTrueWavesurferModel is true.  Also, any properties that should not or could not be cleanly stored in the protocol file (like figures and daq.ni.Session variables) should be stored in a Transient property of the user class, and re-created in the wake() method.  See the user class ws.examples.UserClassWithFigs for examples of how to do this stuff.  And sorry that some of this is not better documented...
