### ISSUE TITLE
Wavesurfer stops responding

### ISSUE THREAD

**Issue by bfearey** [JaneliaSciComp/Wavesurfer#245]
Hi,

I've run into an issue with Wavesurfer eventually crashing after running for a lengthy amount of time (~4-6 hrs). It's particularly problematic when I'm running it while yoking because the communication between scanimage/wavesurfer file naming gets screwed up and won't allow me to acquire unless I restart both programs (including each instance of Matlab)
![image](https://user-images.githubusercontent.com/48023512/61867094-b8501080-aed6-11e9-9914-3edda084fba9.png)
.

The error message is attached.

**Comment by nmlynaryk** [comment]
I am also having issues with Wavesurfer crashing, but it happens within 30min-1hr of recording. The display simply stops scanning and data is no longer written to the h5 file, but there is no error reported in the GUI or in Matlab. Any explanation?

**Comment by adamltaylor** [comment]
Could you please e-mail me at taylora@janelia.hhmi.org?  I'm going to close this issue for now, since a) it's likely two different issues, and b) I'm not sure if bfearey is still having his/her issue.  We can reopen this issue or create a new one later if needed.

In your e-mail, please:
1.  Tell me what version of WaveSurfer, Matlab, the NI-DAQmx Device Driver, and Windows you're using.
2. Tell me what NI card you're using.
3.  Send me a protocol file showing how you've configured WaveSurfer when the problem occurs.
